import 'package:flutter/painting.dart';

/// Placeholder colors: Chigüibara brand mint and ink, plus capybara fur tones.
abstract final class Palette {
  static const mint = Color(0xFFB1F1D7);
  static const ink = Color(0xFF1F1F1F);
  static const blush = Color(0xFFF7A8B8);
  static const fur = Color(0xFFC98B67);
  static const furDark = Color(0xFFA9694A);
  static const furOutline = Color(0xFF6E4330);
  static const muzzle = Color(0xFF8F5A40);
  static const leaf = Color(0xFF5DA65A);
  static const cloud = Color(0xFFFFFFFF);
  static const poop = Color(0xFF8A5A3B);
  static const stink = Color(0xFF8FB04A);
  static const sickTint = Color(0xFF9DBF7A);
  static const sparkle = Color(0xFFF2C14E);
  static const night = Color(0xFF8CC7B2);
  static const sweat = Color(0xFF8FD3F0);
  static const coinRim = Color(0xFFC9932E);
  static const melon = Color(0xFFF07A7A);
  static const orange = Color(0xFFF5A23C);
  static const mouth = Color(0xFF5A2E2A);
  static const beanie = Color(0xFF4FA3A5);
  static const beanieBand = Color(0xFF3B8183);
  static const headphones = Color(0xFFE86A92);
  static const santaRed = Color(0xFFD94848);
  static const santaShade = Color(0xFFB53A3A);
  static const lens = Color(0x5593D4F0);
  static const diving = Color(0xFF2F7FC1);
  static const snorkel = Color(0xFFF2C14E);
  static const scarf = Color(0xFFD95D5D);
  static const ghost = Color(0xFFFAFDFC);
  static const ghostOutline = Color(0xFFB9C4C2);
  static const tree = Color(0xFF3E8E57);
  static const surf = Color(0xFF5CC6D0);
  static const flower = Color(0xFFB58BE0);
  static const grass = Color(0xFF9FDDB0);
  static const path = Color(0xFFE8D3A8);
  static const wizard = Color(0xFF6C4AB6);
  static const wizardBrim = Color(0xFF553A94);
  static const laptop = Color(0xFFB7C0C7);
  static const laptopDark = Color(0xFF8A949C);
  static const bunny = Color(0xFFF7F4F0);
  static const heartLens = Color(0x99F6A5C0);
  static const wrapper = Color(0xFF7FC8E8);
  static const frosting = Color(0xFFF6A5C0);
  static const outside = Color(0xFF2E4A3F);
}
